name: firestore_example
description: Demonstrates how to use the firestore plugin.

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.9.7
  firebase_auth: ^0.8.2

flutter:
  uses-material-design: true
